# Generated by Django 2.2.3 on 2019-08-07 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190807_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='duedate',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='duedatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
